In [3]:
import numpy as np

In [6]:
arr_1d = np.array([1,2,3,4,5])
print("Array id is :",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])

print('2D array is:',arr_2d)

Array id is : [1 2 3 4 5]
2D array is: [[1 2 3]
 [4 5 6]]


### LIST VS NUMPY ARRAY

In [7]:
list =[1,2,3,4]
print("List ultiplid by 2 is:",list * 2)

List ultiplid by 2 is: [1, 2, 3, 4, 1, 2, 3, 4]


In [8]:
arrNp = np.array([1,2,3,4])
print("Numpy array multiplied by 2 is:",arrNp * 2)

Numpy array multiplied by 2 is: [2 4 6 8]


In [9]:
zeroMat =np.zeros([3,4])
print("Zero matrix is:\n",zeroMat)

Zero matrix is:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
onesmat = np.ones([2,3])
print("Ones matrix is:\n",onesmat)


Ones matrix is:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
randomMat = np.random.random([3,4])
print("Random matrix is:\n",randomMat)

Random matrix is:
 [[0.38664974 0.31155314 0.00182914 0.15821845]
 [0.01218114 0.26001254 0.66947136 0.79159027]
 [0.35168106 0.55469087 0.98051244 0.79059319]]
