In [3]:
import numpy as np

In [6]:
arr_1d = np.array([1,2,3,4,5])
print("Array id is :",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])

print('2D array is:',arr_2d)

Array id is : [1 2 3 4 5]
2D array is: [[1 2 3]
 [4 5 6]]


### LIST VS NUMPY ARRAY

In [7]:
list =[1,2,3,4]
print("List ultiplid by 2 is:",list * 2)

List ultiplid by 2 is: [1, 2, 3, 4, 1, 2, 3, 4]


In [8]:
arrNp = np.array([1,2,3,4])
print("Numpy array multiplied by 2 is:",arrNp * 2)

Numpy array multiplied by 2 is: [2 4 6 8]


In [9]:
zeroMat =np.zeros([3,4])
print("Zero matrix is:\n",zeroMat)

Zero matrix is:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
onesmat = np.ones([2,3])
print("Ones matrix is:\n",onesmat)


Ones matrix is:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
randomMat = np.random.random([3,4])
print("Random matrix is:\n",randomMat * 100)

Random matrix is:
 [[58.57624728 44.42580256 89.33559588 46.00589878]
 [96.1856206  81.5331485  96.63929171 50.88372877]
 [71.04347828 27.45104004 74.33200132 43.28539598]]


In [15]:
arrOD = np.arange(11)
print("Array of odd numbers is:",arrOD)

Array of odd numbers is: [ 0  1  2  3  4  5  6  7  8  9 10]


In [16]:
arr = np.array([1,2,3,4])
print("Array shape is:",arr.shape)
arr = arr.reshape(2,2)
print("Reshaped array is:\n",arr)
print("New shape of array is:",arr.shape)   

Array shape is: (4,)
Reshaped array is:
 [[1 2]
 [3 4]]
New shape of array is: (2, 2)
